// <auto-generated />
using DyDashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DyDashboard.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901085350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DyDashboard.Api.Features.Campaigns.Campaign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<double>("ConversionRate")
                        .HasColumnType("REAL")
                        .HasColumnName("conversionRate");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("startDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<int>("Visitors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visitors");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("idx_campaigns_startDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_campaigns_status");

                    b.ToTable("campaigns", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaigns_status", "status IN ('active', 'paused', 'ended')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
